### ISSUE TITLE
Feature: Motoko support

### ISSUE THREAD

**Issue by BrantBrown** [Deland-Labs/dfinity-fungible-token-standard#1]
DFT should support Motoko at the same level as Rust.

**Comment by DelandPro** [comment]
The motoko implementation has been completed, but the call of approve and transfer has not been implemented .

Motoko can not perform call in a generic way
https://github.com/dfinity/motoko/issues/2703 waiting motoko support

**Comment by BrantBrown** [comment]
We've removed motoko implementation, this issue should be closed.
