### ISSUE TITLE
supportedInterface is not necessary

### ISSUE THREAD

**Issue by varik1770** [Deland-Labs/dfinity-fungible-token-standard#2]
Motoko canister support default method __get_candid_interface_tmp_hack to get did, if rust canister implement this method , supportedInterface can be removed from the standard.

```RUST
candid::export_service!();

#[query(name = "__get_candid_interface_tmp_hack")]
#[candid_method(query, rename = "__get_candid_interface_tmp_hack")]
fn __export_did_tmp_() -> String {
    __export_service()
} 
```

After delete supportedInterface  , developer can check canister's interface through __get_candid_interface_tmp_hack.

**Comment by ceempaul** [comment]
True

**Comment by DelandPro** [comment]
Yes. We have removed supportedInterface from Rust implementation, and will remove it from Motoko  implementation later.
> True
